In [1]:
import pandas as pd
income = pd.read_csv("../data/ABS_-_Personal_Income_-_Total_Income_Distribution__SA2__2016-2017.csv/abs_personal_income_total_income_distribution_sa2_2016_17-5794777841303096593.csv")

In [2]:
income

,fid,percentile_ratos_p20_p50_ratio,percentile_ratos_p80_p20_ratio,income_share_top_5pc_pc,median_aud,highest_quartile_pc,median_age_of_earners_years,sa2_code,third_quartile_pc,sa2_name,percentile_ratos_p80_p50_ratio,earners_persons,gini_coefficient_coef,income_share_top_1pc_pc,lowest_quartile_pc,mean_aud,sum_aud,second_quartile_pc,percentile_ratos_p10_p50_ratio,income_share_top_10pc_pc
0,711,0.38,4.89,23.3,58667.0,34.0,33.0,206061136,25.1,Prahran - Windsor,1.87,14996.0,0.480,9.8,20.4,78362.0,1.175122e+09,20.5,0.20,34.5
1,826,0.42,4.17,17.5,51489.0,24.9,44.0,210041240,28.2,Sunbury,1.74,7829.0,0.421,5.8,21.2,60473.0,4.734422e+08,25.7,0.20,28.2
2,827,0.43,3.88,16.2,50727.0,23.0,41.0,210041241,29.7,Sunbury - South,1.69,15982.0,0.401,5.2,20.7,57771.0,9.232882e+08,26.6,0.21,26.6
3,716,0.39,4.62,19.6,56825.0,31.6,33.0,206071141,25.6,Collingwood,1.79,5698.0,0.445,7.0,20.6,69726.0,3.972994e+08,22.2,0.21,30.6
4,825,0.40,4.50,15.7,47312.0,21.1,40.0,210031440,27.7,Hadfield,1.78,2786.0,0.413,4.9,25.0,53617.0,1.493773e+08,26.2,0.18,26.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,984,0.33,6.43,26.5,54529.0,34.6,49.0,214021381,19.3,Mount Eliza,2.13,11375.0,0.540,11.4,24.7,81583.0,9.280054e+08,21.3,0.13,38.5
305,985,0.36,5.63,22.7,49040.0,28.9,47.0,214021382,21.6,Mount Martha,2.03,11318.0,0.499,9.3,25.2,66615.0,7.539468e+08,24.3,0.16,34.3
306,986,0.37,5.34,31.3,39267.0,18.5,50.0,214021383,22.2,Point Nepean,2.00,10236.0,0.554,17.4,30.2,59717.0,6.112650e+08,29.1,0.15,41.9
307,987,0.35,5.29,18.3,37748.0,14.7,48.0,214021384,23.3,Rosebud - McCrae,1.87,10868.0,0.455,6.1,32.1,45524.0,4.947539e+08,30.0,0.14,29.5
308,988,0.42,4.18,18.2,47929.0,22.0,44.0,214021385,27.6,Somerville,1.77,11166.0,0.427,6.3,22.5,57071.0,6.372600e+08,27.9,0.21,28.8

In [3]:
import geopandas as gpd
import shapely
shapely.speedups.disable()
# GeoDataFrame creation
poly = gpd.read_file("../data/1270055001_sa2_2016_aust_shape/SA2_2016_AUST.shp")
poly

,SA2_MAIN16,SA2_5DIG16,SA2_NAME16,SA3_CODE16,SA3_NAME16,SA4_CODE16,SA4_NAME16,GCC_CODE16,GCC_NAME16,STE_CODE16,STE_NAME16,AREASQKM16,geometry
0,101021007,11007,Braidwood,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,3418.3525,"POLYGON ((149.58423 -35.44427, 149.58444 -35.4..."
1,101021008,11008,Karabar,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,6.9825,"POLYGON ((149.21898 -35.36739, 149.21799 -35.3..."
2,101021009,11009,Queanbeyan,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,4.7634,"POLYGON ((149.21325 -35.34325, 149.21619 -35.3..."
3,101021010,11010,Queanbeyan - East,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,13.0034,"POLYGON ((149.24033 -35.34782, 149.24023 -35.3..."
4,101021011,11011,Queanbeyan Region,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,3054.4099,"POLYGON ((149.23580 -35.38738, 149.23771 -35.3..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,901021002,91002,Cocos (Keeling) Islands,90102,Cocos (Keeling) Islands,901,Other Territories,9OTER,Other Territories,9,Other Territories,13.7163,"MULTIPOLYGON (((96.83047 -12.17636, 96.83045 -..."
2306,901031003,91003,Jervis Bay,90103,Jervis Bay,901,Other Territories,9OTER,Other Territories,9,Other Territories,67.8134,"MULTIPOLYGON (((150.69566 -35.18297, 150.69555..."
2307,901041004,91004,Norfolk Island,90104,Norfolk Island,901,Other Territories,9OTER,Other Territories,9,Other Territories,38.6509,"MULTIPOLYGON (((167.99472 -29.04534, 167.99432..."
2308,997979799,99799,Migratory - Offshore - Shipping (OT),99797,Migratory - Offshore - Shipping (OT),997,Migratory - Offshore - Shipping (OT),99799,Migratory - Offshore - Shipping (OT),9,Other Territories,0.0000,None
2309,999999499,99499,No usual address (OT),99999,No usual address (OT),999,No usual address (OT),99499,No usual address (OT),9,Other Territories,0.0000,None

In [4]:
rent = pd.read_csv("../data/abs_data_by_region_family_and_community_asgs_sa2_2011_2018-2557324081243514741.csv")

In [5]:
rent

,rnt_mrtgge_pymnts_cnss_avrge_mnthly_hshld_rntl_pymnt,yr,sa2_maincode_2016,rent_mortgage_payments_census_average_monthly_household_payment
0,NaN,2016,208031192,NaN
1,1466.0,2016,211051281,1844.0
2,1427.0,2016,211051282,1916.0
3,1110.0,2016,211051286,1538.0
4,1529.0,2016,212011287,2004.0
...,...,...,...,...
304,1753.0,2016,214011376,1963.0
305,1432.0,2016,214021377,1811.0
306,1317.0,2016,214021378,2280.0
307,1214.0,2016,214021384,1560.0
308,1360.0,2016,214021385,1743.0

In [6]:
jobseek = pd.read_csv("../data/dss_quarterly_payment_recipients_sa2_jun_2020-6190584206522296761.csv")

In [21]:
import json
file_name = "../data/ave_pos_score_dict.json"
with open(file_name,'r',encoding='utf-8') as f:
    ave_pos_score_dict = json.load(f)
sa2_maincode_2016 = ave_pos_score_dict.keys()
pos_score_list = []
for i in sa2_maincode_2016:
    pos_score_list.append(ave_pos_score_dict[i])
from pandas.core.frame import DataFrame
c={"sa2_maincode_2016" : sa2_maincode_2016,
   "pos_score" : pos_score_list}
pos_score=DataFrame(c)
print(pos_score)

    sa2_maincode_2016  pos_score
0           206011105   0.120654
1           206011106   0.114565
2           206011107   0.149488
3           206011108   0.112907
4           206011109   0.162807
..                ...        ...
299         214011376   0.148097
300         214021380   0.139384
301         214021381   0.189506
302         214021382   0.124204
303         214021385   0.173260

[304 rows x 2 columns]

In [20]:
import json
file_name = "../data/ave_compound_score_dic.json"
with open(file_name,'r',encoding='utf-8') as f:
    ave_compound_score_dict = json.load(f)
sa2_maincode_2016 = ave_compound_score_dict.keys()
compound_score_list = []
for i in sa2_maincode_2016:
    compound_score_list.append(ave_compound_score_dict[i])
from pandas.core.frame import DataFrame
c={"sa2_maincode_2016" : sa2_maincode_2016,
   "compound_score" : compound_score_list}
compound_score=DataFrame(c)
print(compound_score)

    sa2_maincode_2016  compound_score
0           206011105        0.135939
1           206011106        0.145158
2           206011107        0.161915
3           206011108        0.110326
4           206011109        0.220207
..                ...             ...
299         214011376        0.110310
300         214021380        0.195167
301         214021381        0.216418
302         214021382        0.132294
303         214021385        0.210186

[304 rows x 2 columns]

In [19]:
import json
file_name = "../data/ave_neu_score_dict.json"
with open(file_name,'r',encoding='utf-8') as f:
    ave_neu_score_dict = json.load(f)
sa2_maincode_2016 = ave_neu_score_dict.keys()
neu_score_list = []
for i in sa2_maincode_2016:
    neu_score_list.append(ave_neu_score_dict[i])
from pandas.core.frame import DataFrame
c={"sa2_maincode_2016" : sa2_maincode_2016,
   "neu_score" : neu_score_list}
neu_score=DataFrame(c)
print(neu_score)

    sa2_maincode_2016  neu_score
0           206011105   0.832922
1           206011106   0.844753
2           206011107   0.795355
3           206011108   0.834144
4           206011109   0.788827
..                ...        ...
299         214011376   0.772802
300         214021380   0.826098
301         214021381   0.755194
302         214021382   0.809335
303         214021385   0.774622

[304 rows x 2 columns]

In [24]:
import json
file_name = "../data/ave_neg_score_dict.json"
with open(file_name,'r',encoding='utf-8') as f:
    ave_neg_score_dict = json.load(f)
sa2_maincode_2016 = ave_neu_score_dict.keys()
neg_score_list = []
for i in sa2_maincode_2016:
    neg_score_list.append(ave_neg_score_dict[i])
from pandas.core.frame import DataFrame
c={"sa2_maincode_2016" : sa2_maincode_2016,
   "compound_score" : compound_score_list,
   "pos_score" : pos_score_list,
   "neu_score" : neg_score_list,
  "neg_score" : neg_score_list}
all_score=DataFrame(c)
print(all_score)

    sa2_maincode_2016  compound_score  pos_score  neu_score  neg_score
0           206011105        0.135939   0.120654   0.046423   0.046423
1           206011106        0.145158   0.114565   0.040679   0.040679
2           206011107        0.161915   0.149488   0.055161   0.055161
3           206011108        0.110326   0.112907   0.052949   0.052949
4           206011109        0.220207   0.162807   0.048373   0.048373
..                ...             ...        ...        ...        ...
299         214011376        0.110310   0.148097   0.078747   0.078747
300         214021380        0.195167   0.139384   0.034515   0.034515
301         214021381        0.216418   0.189506   0.055296   0.055296
302         214021382        0.132294   0.124204   0.066461   0.066461
303         214021385        0.210186   0.173260   0.052122   0.052122

[304 rows x 5 columns]

In [25]:
income

,fid,percentile_ratos_p20_p50_ratio,percentile_ratos_p80_p20_ratio,income_share_top_5pc_pc,median_aud,highest_quartile_pc,median_age_of_earners_years,sa2_code,third_quartile_pc,sa2_name,percentile_ratos_p80_p50_ratio,earners_persons,gini_coefficient_coef,income_share_top_1pc_pc,lowest_quartile_pc,mean_aud,sum_aud,second_quartile_pc,percentile_ratos_p10_p50_ratio,income_share_top_10pc_pc
0,711,0.38,4.89,23.3,58667.0,34.0,33.0,206061136,25.1,Prahran - Windsor,1.87,14996.0,0.480,9.8,20.4,78362.0,1.175122e+09,20.5,0.20,34.5
1,826,0.42,4.17,17.5,51489.0,24.9,44.0,210041240,28.2,Sunbury,1.74,7829.0,0.421,5.8,21.2,60473.0,4.734422e+08,25.7,0.20,28.2
2,827,0.43,3.88,16.2,50727.0,23.0,41.0,210041241,29.7,Sunbury - South,1.69,15982.0,0.401,5.2,20.7,57771.0,9.232882e+08,26.6,0.21,26.6
3,716,0.39,4.62,19.6,56825.0,31.6,33.0,206071141,25.6,Collingwood,1.79,5698.0,0.445,7.0,20.6,69726.0,3.972994e+08,22.2,0.21,30.6
4,825,0.40,4.50,15.7,47312.0,21.1,40.0,210031440,27.7,Hadfield,1.78,2786.0,0.413,4.9,25.0,53617.0,1.493773e+08,26.2,0.18,26.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,984,0.33,6.43,26.5,54529.0,34.6,49.0,214021381,19.3,Mount Eliza,2.13,11375.0,0.540,11.4,24.7,81583.0,9.280054e+08,21.3,0.13,38.5
305,985,0.36,5.63,22.7,49040.0,28.9,47.0,214021382,21.6,Mount Martha,2.03,11318.0,0.499,9.3,25.2,66615.0,7.539468e+08,24.3,0.16,34.3
306,986,0.37,5.34,31.3,39267.0,18.5,50.0,214021383,22.2,Point Nepean,2.00,10236.0,0.554,17.4,30.2,59717.0,6.112650e+08,29.1,0.15,41.9
307,987,0.35,5.29,18.3,37748.0,14.7,48.0,214021384,23.3,Rosebud - McCrae,1.87,10868.0,0.455,6.1,32.1,45524.0,4.947539e+08,30.0,0.14,29.5
308,988,0.42,4.18,18.2,47929.0,22.0,44.0,214021385,27.6,Somerville,1.77,11166.0,0.427,6.3,22.5,57071.0,6.372600e+08,27.9,0.21,28.8

In [30]:
income["sa2_maincode_2016"] = income[" sa2_code"] 
str_sa2_maincode_2016 = []
for i in list(income["sa2_maincode_2016"]):
    str_sa2_maincode_2016.append(str(i))
income["sa2_maincode_2016"] = str_sa2_maincode_2016

In [31]:
final_df = all_score.merge(income, on = "sa2_maincode_2016")

In [32]:
final_df

,sa2_maincode_2016,compound_score,pos_score,neu_score,neg_score,fid,percentile_ratos_p20_p50_ratio,percentile_ratos_p80_p20_ratio,income_share_top_5pc_pc,median_aud,...,percentile_ratos_p80_p50_ratio,earners_persons,gini_coefficient_coef,income_share_top_1pc_pc,lowest_quartile_pc,mean_aud,sum_aud,second_quartile_pc,percentile_ratos_p10_p50_ratio,income_share_top_10pc_pc
0,206011105,0.135939,0.120654,0.046423,0.046423,680,0.38,4.89,18.7,51576.0,...,1.85,17741.0,0.450,6.3,23.3,63199.0,1.121215e+09,23.8,0.19,29.9
1,206011106,0.145158,0.114565,0.040679,0.040679,681,0.38,4.66,17.9,54618.0,...,1.77,7948.0,0.432,5.7,22.0,64629.0,5.136729e+08,22.3,0.19,28.7
2,206011107,0.161915,0.149488,0.055161,0.055161,682,0.38,4.84,18.5,50643.0,...,1.85,8887.0,0.444,6.0,23.4,62166.0,5.524692e+08,24.4,0.18,29.6
3,206011108,0.110326,0.112907,0.052949,0.052949,683,0.39,4.76,17.8,50613.0,...,1.84,15929.0,0.439,5.8,23.3,61246.0,9.755821e+08,24.7,0.18,28.9
4,206011109,0.220207,0.162807,0.048373,0.048373,684,0.39,4.62,17.8,55080.0,...,1.80,6140.0,0.435,5.8,21.1,66374.0,4.075345e+08,22.9,0.20,28.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,214011376,0.110310,0.148097,0.078747,0.078747,979,0.44,3.92,17.5,52393.0,...,1.73,7926.0,0.411,5.8,19.5,62010.0,4.914878e+08,26.2,0.24,28.0
300,214021380,0.195167,0.139384,0.034515,0.034515,983,0.37,5.31,21.9,44686.0,...,1.95,14175.0,0.483,8.8,27.3,58594.0,8.305660e+08,26.2,0.15,33.2
301,214021381,0.216418,0.189506,0.055296,0.055296,984,0.33,6.43,26.5,54529.0,...,2.13,11375.0,0.540,11.4,24.7,81583.0,9.280054e+08,21.3,0.13,38.5
302,214021382,0.132294,0.124204,0.066461,0.066461,985,0.36,5.63,22.7,49040.0,...,2.03,11318.0,0.499,9.3,25.2,66615.0,7.539468e+08,24.3,0.16,34.3
303,214021385,0.210186,0.173260,0.052122,0.052122,988,0.42,4.18,18.2,47929.0,...,1.77,11166.0,0.427,6.3,22.5,57071.0,6.372600e+08,27.9,0.21,28.8

In [33]:
str_sa2_maincode_2016 = []
for i in list(poly["SA2_MAIN16"]):
    str_sa2_maincode_2016.append(str(i))
poly["sa2_maincode_2016"] = str_sa2_maincode_2016

In [35]:
final_df = final_df.merge(poly, on = "sa2_maincode_2016")

In [36]:
final_df

,sa2_maincode_2016,compound_score,pos_score,neu_score,neg_score,fid,percentile_ratos_p20_p50_ratio,percentile_ratos_p80_p20_ratio,income_share_top_5pc_pc,median_aud,...,SA3_CODE16,SA3_NAME16,SA4_CODE16,SA4_NAME16,GCC_CODE16,GCC_NAME16,STE_CODE16,STE_NAME16,AREASQKM16,geometry
0,206011105,0.135939,0.120654,0.046423,0.046423,680,0.38,4.89,18.7,51576.0,...,20601,Brunswick - Coburg,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,5.1425,"POLYGON ((144.94974 -37.76277, 144.95003 -37.7..."
1,206011106,0.145158,0.114565,0.040679,0.040679,681,0.38,4.66,17.9,54618.0,...,20601,Brunswick - Coburg,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,2.1680,"POLYGON ((144.97340 -37.76204, 144.97335 -37.7..."
2,206011107,0.161915,0.149488,0.055161,0.055161,682,0.38,4.84,18.5,50643.0,...,20601,Brunswick - Coburg,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,3.1795,"POLYGON ((144.93407 -37.75969, 144.93405 -37.7..."
3,206011108,0.110326,0.112907,0.052949,0.052949,683,0.39,4.76,17.8,50613.0,...,20601,Brunswick - Coburg,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,6.9346,"POLYGON ((144.94847 -37.73951, 144.94878 -37.7..."
4,206011109,0.220207,0.162807,0.048373,0.048373,684,0.39,4.62,17.8,55080.0,...,20601,Brunswick - Coburg,206,Melbourne - Inner,2GMEL,Greater Melbourne,2,Victoria,2.9887,"POLYGON ((144.93264 -37.74226, 144.93251 -37.7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,214011376,0.110310,0.148097,0.078747,0.078747,979,0.44,3.92,17.5,52393.0,...,21401,Frankston,214,Mornington Peninsula,2GMEL,Greater Melbourne,2,Victoria,19.8152,"POLYGON ((145.20155 -38.08045, 145.20178 -38.0..."
300,214021380,0.195167,0.139384,0.034515,0.034515,983,0.37,5.31,21.9,44686.0,...,21402,Mornington Peninsula,214,Mornington Peninsula,2GMEL,Greater Melbourne,2,Victoria,21.0928,"POLYGON ((145.03077 -38.22462, 145.03110 -38.2..."
301,214021381,0.216418,0.189506,0.055296,0.055296,984,0.33,6.43,26.5,54529.0,...,21402,Mornington Peninsula,214,Mornington Peninsula,2GMEL,Greater Melbourne,2,Victoria,23.2077,"POLYGON ((145.07201 -38.18710, 145.07216 -38.1..."
302,214021382,0.132294,0.124204,0.066461,0.066461,985,0.36,5.63,22.7,49040.0,...,21402,Mornington Peninsula,214,Mornington Peninsula,2GMEL,Greater Melbourne,2,Victoria,30.2094,"POLYGON ((145.02584 -38.25242, 145.02616 -38.2..."
303,214021385,0.210186,0.173260,0.052122,0.052122,988,0.42,4.18,18.2,47929.0,...,21402,Mornington Peninsula,214,Mornington Peninsula,2GMEL,Greater Melbourne,2,Victoria,117.3540,"POLYGON ((145.09285 -38.23093, 145.09924 -38.2..."

In [39]:
str_sa2_maincode_2016 = []
for i in list(rent[" sa2_maincode_2016"]):
    str_sa2_maincode_2016.append(str(i))
rent["sa2_maincode_2016"] = str_sa2_maincode_2016
final_df = final_df.merge(rent, on = "sa2_maincode_2016")
final_df

,sa2_maincode_2016,compound_score,pos_score,neu_score,neg_score,fid,percentile_ratos_p20_p50_ratio,percentile_ratos_p80_p20_ratio,income_share_top_5pc_pc,median_aud,...,GCC_CODE16,GCC_NAME16,STE_CODE16,STE_NAME16,AREASQKM16,geometry,rnt_mrtgge_pymnts_cnss_avrge_mnthly_hshld_rntl_pymnt,yr,sa2_maincode_2016,rent_mortgage_payments_census_average_monthly_household_payment
0,206011105,0.135939,0.120654,0.046423,0.046423,680,0.38,4.89,18.7,51576.0,...,2GMEL,Greater Melbourne,2,Victoria,5.1425,"POLYGON ((144.94974 -37.76277, 144.95003 -37.7...",1824.0,2016,206011105,2240.0
1,206011106,0.145158,0.114565,0.040679,0.040679,681,0.38,4.66,17.9,54618.0,...,2GMEL,Greater Melbourne,2,Victoria,2.1680,"POLYGON ((144.97340 -37.76204, 144.97335 -37.7...",1840.0,2016,206011106,2218.0
2,206011107,0.161915,0.149488,0.055161,0.055161,682,0.38,4.84,18.5,50643.0,...,2GMEL,Greater Melbourne,2,Victoria,3.1795,"POLYGON ((144.93407 -37.75969, 144.93405 -37.7...",1494.0,2016,206011107,2144.0
3,206011108,0.110326,0.112907,0.052949,0.052949,683,0.39,4.76,17.8,50613.0,...,2GMEL,Greater Melbourne,2,Victoria,6.9346,"POLYGON ((144.94847 -37.73951, 144.94878 -37.7...",1642.0,2016,206011108,2135.0
4,206011109,0.220207,0.162807,0.048373,0.048373,684,0.39,4.62,17.8,55080.0,...,2GMEL,Greater Melbourne,2,Victoria,2.9887,"POLYGON ((144.93264 -37.74226, 144.93251 -37.7...",1609.0,2016,206011109,2136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,214011376,0.110310,0.148097,0.078747,0.078747,979,0.44,3.92,17.5,52393.0,...,2GMEL,Greater Melbourne,2,Victoria,19.8152,"POLYGON ((145.20155 -38.08045, 145.20178 -38.0...",1753.0,2016,214011376,1963.0
300,214021380,0.195167,0.139384,0.034515,0.034515,983,0.37,5.31,21.9,44686.0,...,2GMEL,Greater Melbourne,2,Victoria,21.0928,"POLYGON ((145.03077 -38.22462, 145.03110 -38.2...",1440.0,2016,214021380,1842.0
301,214021381,0.216418,0.189506,0.055296,0.055296,984,0.33,6.43,26.5,54529.0,...,2GMEL,Greater Melbourne,2,Victoria,23.2077,"POLYGON ((145.07201 -38.18710, 145.07216 -38.1...",1923.0,2016,214021381,2422.0
302,214021382,0.132294,0.124204,0.066461,0.066461,985,0.36,5.63,22.7,49040.0,...,2GMEL,Greater Melbourne,2,Victoria,30.2094,"POLYGON ((145.02584 -38.25242, 145.02616 -38.2...",1791.0,2016,214021382,2094.0
303,214021385,0.210186,0.173260,0.052122,0.052122,988,0.42,4.18,18.2,47929.0,...,2GMEL,Greater Melbourne,2,Victoria,117.3540,"POLYGON ((145.09285 -38.23093, 145.09924 -38.2...",1360.0,2016,214021385,1743.0

In [40]:
jobseek

,low_income_card_censored,health_care_card,sa2_main16,jobseeker_payment
0,False,3644,206011105,1964
1,False,1617,206011106,829
2,False,1819,206011107,1011
3,False,3224,206011108,1767
4,False,951,206011109,459
...,...,...,...,...
304,False,1041,214021381,474
305,False,1335,214021382,623
306,False,1801,214021383,1132
307,False,2317,214021384,1563
308,False,1631,214021385,858

In [41]:
str_sa2_maincode_2016 = []
for i in list(jobseek[" sa2_main16"]):
    str_sa2_maincode_2016.append(str(i))
jobseek["sa2_maincode_2016"] = str_sa2_maincode_2016
final_df = final_df.merge(jobseek, on = "sa2_maincode_2016")
final_df

,sa2_maincode_2016,compound_score,pos_score,neu_score,neg_score,fid,percentile_ratos_p20_p50_ratio,percentile_ratos_p80_p20_ratio,income_share_top_5pc_pc,median_aud,...,AREASQKM16,geometry,rnt_mrtgge_pymnts_cnss_avrge_mnthly_hshld_rntl_pymnt,yr,sa2_maincode_2016,rent_mortgage_payments_census_average_monthly_household_payment,low_income_card_censored,health_care_card,sa2_main16,jobseeker_payment
0,206011105,0.135939,0.120654,0.046423,0.046423,680,0.38,4.89,18.7,51576.0,...,5.1425,"POLYGON ((144.94974 -37.76277, 144.95003 -37.7...",1824.0,2016,206011105,2240.0,False,3644,206011105,1964
1,206011106,0.145158,0.114565,0.040679,0.040679,681,0.38,4.66,17.9,54618.0,...,2.1680,"POLYGON ((144.97340 -37.76204, 144.97335 -37.7...",1840.0,2016,206011106,2218.0,False,1617,206011106,829
2,206011107,0.161915,0.149488,0.055161,0.055161,682,0.38,4.84,18.5,50643.0,...,3.1795,"POLYGON ((144.93407 -37.75969, 144.93405 -37.7...",1494.0,2016,206011107,2144.0,False,1819,206011107,1011
3,206011108,0.110326,0.112907,0.052949,0.052949,683,0.39,4.76,17.8,50613.0,...,6.9346,"POLYGON ((144.94847 -37.73951, 144.94878 -37.7...",1642.0,2016,206011108,2135.0,False,3224,206011108,1767
4,206011109,0.220207,0.162807,0.048373,0.048373,684,0.39,4.62,17.8,55080.0,...,2.9887,"POLYGON ((144.93264 -37.74226, 144.93251 -37.7...",1609.0,2016,206011109,2136.0,False,951,206011109,459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,214011376,0.110310,0.148097,0.078747,0.078747,979,0.44,3.92,17.5,52393.0,...,19.8152,"POLYGON ((145.20155 -38.08045, 145.20178 -38.0...",1753.0,2016,214011376,1963.0,False,1164,214011376,561
300,214021380,0.195167,0.139384,0.034515,0.034515,983,0.37,5.31,21.9,44686.0,...,21.0928,"POLYGON ((145.03077 -38.22462, 145.03110 -38.2...",1440.0,2016,214021380,1842.0,False,2117,214021380,1169
301,214021381,0.216418,0.189506,0.055296,0.055296,984,0.33,6.43,26.5,54529.0,...,23.2077,"POLYGON ((145.07201 -38.18710, 145.07216 -38.1...",1923.0,2016,214021381,2422.0,False,1041,214021381,474
302,214021382,0.132294,0.124204,0.066461,0.066461,985,0.36,5.63,22.7,49040.0,...,30.2094,"POLYGON ((145.02584 -38.25242, 145.02616 -38.2...",1791.0,2016,214021382,2094.0,False,1335,214021382,623
303,214021385,0.210186,0.173260,0.052122,0.052122,988,0.42,4.18,18.2,47929.0,...,117.3540,"POLYGON ((145.09285 -38.23093, 145.09924 -38.2...",1360.0,2016,214021385,1743.0,False,1631,214021385,858

In [42]:
final_df.columns

Index(['sa2_maincode_2016', 'compound_score', 'pos_score', 'neu_score',
       'neg_score', 'fid', ' percentile_ratos_p20_p50_ratio',
       ' percentile_ratos_p80_p20_ratio', ' income_share_top_5pc_pc',
       ' median_aud', ' highest_quartile_pc', ' median_age_of_earners_years',
       ' sa2_code', ' third_quartile_pc', ' sa2_name',
       ' percentile_ratos_p80_p50_ratio', ' earners_persons',
       ' gini_coefficient_coef', ' income_share_top_1pc_pc',
       ' lowest_quartile_pc', ' mean_aud', ' sum_aud', ' second_quartile_pc',
       ' percentile_ratos_p10_p50_ratio', ' income_share_top_10pc_pc',
       'SA2_MAIN16', 'SA2_5DIG16', 'SA2_NAME16', 'SA3_CODE16', 'SA3_NAME16',
       'SA4_CODE16', 'SA4_NAME16', 'GCC_CODE16', 'GCC_NAME16', 'STE_CODE16',
       'STE_NAME16', 'AREASQKM16', 'geometry',
       'rnt_mrtgge_pymnts_cnss_avrge_mnthly_hshld_rntl_pymnt', ' yr',
       ' sa2_maincode_2016',
       ' rent_mortgage_payments_census_average_monthly_household_payment',
       'low_income_card_censored', ' health_care_card', ' sa2_main16',
       ' jobseeker_payment'],
      dtype='object')

In [44]:
name_list = list(final_df[" sa2_name"])

In [49]:

name_all =""
for i in name_list:
    name_all =name_all + i

In [51]:
print("Dockland" in name_all)

True

In [48]:
name_list

['Brunswick',
 'Brunswick East',
 'Brunswick West',
 'Coburg',
 'Pascoe Vale South',
 'Alphington - Fairfield',
 'Northcote',
 'Thornbury',
 'Ascot Vale',
 'Essendon - Aberfeldie',
 'Flemington',
 'Moonee Ponds',
 'Carlton',
 'Docklands',
 'East Melbourne',
 'Flemington Racecourse',
 'Kensington (Vic.)',
 'Melbourne',
 'North Melbourne',
 'Parkville',
 'South Yarra - West',
 'Southbank',
 'West Melbourne',
 'Albert Park',
 'Elwood',
 'Port Melbourne',
 'Port Melbourne Industrial',
 'South Melbourne',
 'St Kilda',
 'St Kilda East',
 'Armadale',
 'Prahran - Windsor',
 'South Yarra - East',
 'Toorak',
 'Abbotsford',
 'Carlton North - Princes Hill',
 'Collingwood',
 'Fitzroy',
 'Fitzroy North',
 'Richmond (Vic.)',
 'Yarra - North',
 'Ashburton (Vic.)',
 'Balwyn',
 'Balwyn North',
 'Camberwell',
 'Glen Iris - East',
 'Hawthorn',
 'Hawthorn East',
 'Kew',
 'Kew East',
 'Surrey Hills (West) - Canterbury',
 'Bulleen',
 'Doncaster',
 'Templestowe',
 'Templestowe Lower',
 'Doncaster East (North)',
 'Doncaster East (South)',
 'Blackburn',
 'Blackburn South',
 'Box Hill',
 'Box Hill North',
 'Burwood',
 'Burwood East',
 'Surrey Hills (East) - Mont Albert',
 'Beaumaris',
 'Brighton (Vic.)',
 'Brighton East',
 'Cheltenham - Highett (West)',
 'Hampton',
 'Sandringham - Black Rock',
 'Bentleigh - McKinnon',
 'Carnegie',
 'Caulfield - North',
 'Caulfield - South',
 'Elsternwick',
 'Hughesdale',
 'Murrumbeena',
 'Ormond - Glen Huntly',
 'Bentleigh East (North)',
 'Bentleigh East (South)',
 'Aspendale Gardens - Waterways',
 'Braeside',
 'Carrum - Patterson Lakes',
 'Chelsea - Bonbeach',
 'Chelsea Heights',
 'Cheltenham - Highett (East)',
 'Edithvale - Aspendale',
 'Mentone',
 'Moorabbin - Heatherton',
 'Moorabbin Airport',
 'Mordialloc - Parkdale',
 'Malvern - Glen Iris',
 'Malvern East',
 'Bundoora - East',
 'Greensborough',
 'Heidelberg - Rosanna',
 'Heidelberg West',
 'Ivanhoe',
 'Ivanhoe East - Eaglemont',
 'Montmorency - Briar Hill',
 'Viewbank - Yallambie',
 'Watsonia',
 'Kingsbury',
 'Reservoir - East',
 'Reservoir - West',
 'Preston - East',
 'Preston - West',
 'Eltham',
 'Hurstbridge',
 'Kinglake',
 'Panton Hill - St Andrews',
 'Plenty - Yarrambat',
 'Research - North Warrandyte',
 'Wattle Glen - Diamond Creek',
 'Bundoora - North',
 'Bundoora - West',
 'Lalor',
 'Mill Park - North',
 'Mill Park - South',
 'Thomastown',
 'Wallan',
 'Whittlesea',
 'Doreen',
 'Epping - East',
 'Epping - South',
 'Epping - West',
 'Mernda',
 'South Morang (North)',
 'South Morang (South)',
 'Wollert',
 'Airport West',
 'Essendon Airport',
 'Keilor',
 'Keilor East',
 'Niddrie - Essendon West',
 'Strathmore',
 'Gisborne',
 'Macedon',
 'Riddells Creek',
 'Romsey',
 'Coburg North',
 'Fawkner',
 'Pascoe Vale',
 'Glenroy',
 'Gowanbrae',
 'Hadfield',
 'Sunbury',
 'Sunbury - South',
 'Broadmeadows',
 'Campbellfield - Coolaroo',
 'Gladstone Park - Westmeadows',
 'Greenvale - Bulla',
 'Meadow Heights',
 'Melbourne Airport',
 'Roxburgh Park - Somerton',
 'Tullamarine',
 'Craigieburn - Central',
 'Craigieburn - North',
 'Craigieburn - South',
 'Craigieburn - West',
 'Mickleham - Yuroke',
 'Bayswater',
 'Knoxfield - Scoresby',
 'Lysterfield',
 'Rowville - Central',
 'Rowville - North',
 'Rowville - South',
 'Wantirna',
 'Wantirna South',
 'Boronia',
 'Ferntree Gully (North)',
 'Ferntree Gully (South) - Upper Ferntree Gully',
 'The Basin',
 'Donvale - Park Orchards',
 'Warrandyte - Wonga Park',
 'Bayswater North',
 'Croydon Hills - Warranwood',
 'Ringwood',
 'Ringwood East',
 'Ringwood North',
 'Croydon - East',
 'Croydon - West',
 'Croydon South',
 'Forest Hill',
 'Mitcham (Vic.)',
 'Nunawading',
 'Vermont',
 'Vermont South',
 'Belgrave - Selby',
 'Chirnside Park',
 'Healesville - Yarra Glen',
 'Kilsyth',
 'Lilydale - Coldstream',
 'Monbulk - Silvan',
 'Montrose',
 'Mooroolbark',
 'Mount Dandenong - Olinda',
 'Mount Evelyn',
 'Upwey - Tecoma',
 'Wandin - Seville',
 'Yarra Valley',
 'Beaconsfield - Officer',
 'Bunyip - Garfield',
 'Emerald - Cockatoo',
 'Koo Wee Rup',
 'Pakenham - North',
 'Pakenham - South',
 'Berwick - North',
 'Berwick - South',
 'Doveton',
 'Hallam',
 'Narre Warren North',
 'Endeavour Hills - North',
 'Endeavour Hills - South',
 'Narre Warren - North East',
 'Narre Warren - South West',
 'Cranbourne',
 'Cranbourne East',
 'Cranbourne North',
 'Cranbourne South',
 'Cranbourne West',
 'Hampton Park - Lynbrook',
 'Lynbrook - Lyndhurst',
 'Pearcedale - Tooradin',
 'Narre Warren South (East)',
 'Narre Warren South (West)',
 'Clarinda - Oakleigh South',
 'Clayton South',
 'Dandenong',
 'Dandenong North',
 'Dingley Village',
 'Keysborough',
 'Noble Park North',
 'Springvale',
 'Springvale South',
 'Noble Park - East',
 'Noble Park - West',
 'Ashwood - Chadstone',
 'Clayton',
 'Glen Waverley - East',
 'Glen Waverley - West',
 'Mount Waverley - North',
 'Mount Waverley - South',
 'Mulgrave',
 'Oakleigh - Huntingdale',
 'Wheelers Hill',
 'Ardeer - Albion',
 'Cairnlea',
 'Deer Park - Derrimut',
 'Delahey',
 'Keilor Downs',
 'Kings Park (Vic.)',
 'St Albans - North',
 'St Albans - South',
 'Sunshine',
 'Sunshine North',
 'Sunshine West',
 'Sydenham',
 'Taylors Lakes',
 'Altona',
 'Altona Meadows',
 'Altona North',
 'Newport',
 'Seabrook',
 'Williamstown',
 'Braybrook',
 'Footscray',
 'Maribyrnong',
 'Seddon - Kingsville',
 'West Footscray - Tottenham',
 'Yarraville',
 'Bacchus Marsh',
 'Hillside',
 'Melton',
 'Melton South',
 'Melton West',
 'Rockbank - Mount Cottrell',
 'Taylors Hill',
 'Burnside',
 'Burnside Heights',
 'Caroline Springs',
 'Hoppers Crossing - North',
 'Hoppers Crossing - South',
 'Laverton',
 'Tarneit',
 'Truganina',
 'Werribee - South',
 'Wyndham Vale',
 'Point Cook - East',
 'Point Cook - North',
 'Point Cook - South',
 'Werribee - East',
 'Werribee - West',
 'Carrum Downs',
 'Frankston',
 'Frankston North',
 'Frankston South',
 'Langwarrin',
 'Seaford (Vic.)',
 'Skye - Sandhurst',
 'Mornington',
 'Mount Eliza',
 'Mount Martha',
 'Somerville']

In [56]:
name_list.index("Mornington")

300

In [57]:
name_list = ["Melbourne","Brunswick","Docklands","Footscray",'Surrey Hills (West) - Canterbury',"Camberwell","Dandenong","Mornington"]

In [63]:
sub8_all_info = final_df[final_df[" sa2_name"].isin(name_list)]

In [68]:
final_df.to_csv("../data/sa2_old_all_513.csv",index = False)

In [64]:
sub8_all_info

,sa2_maincode_2016,compound_score,pos_score,neu_score,neg_score,fid,percentile_ratos_p20_p50_ratio,percentile_ratos_p80_p20_ratio,income_share_top_5pc_pc,median_aud,...,AREASQKM16,geometry,rnt_mrtgge_pymnts_cnss_avrge_mnthly_hshld_rntl_pymnt,yr,sa2_maincode_2016,rent_mortgage_payments_census_average_monthly_household_payment,low_income_card_censored,health_care_card,sa2_main16,jobseeker_payment
0,206011105,0.135939,0.120654,0.046423,0.046423,680,0.38,4.89,18.7,51576.0,...,5.1425,"POLYGON ((144.94974 -37.76277, 144.95003 -37.7...",1824.0,2016,206011105,2240.0,False,3644,206011105,1964
13,206041118,0.143549,0.111991,0.037171,0.037171,693,0.32,6.07,23.8,51342.0,...,2.4440,"POLYGON ((144.93238 -37.81927, 144.93287 -37.8...",2308.0,2016,206041118,2408.0,False,851,206041118,531
17,206041122,0.135247,0.096241,0.028379,0.028379,697,0.31,8.57,31.0,28068.0,...,2.3690,"POLYGON ((144.96489 -37.80687, 144.96511 -37.8...",2047.0,2016,206041122,1841.0,False,2725,206041122,1672
44,207011149,0.123440,0.110495,0.050475,0.050475,724,0.31,7.51,30.6,57447.0,...,7.2919,"POLYGON ((145.05762 -37.82654, 145.05775 -37.8...",2115.0,2016,207011149,2718.0,False,1389,207011149,555
50,207011155,0.152065,0.139154,0.053066,0.053066,730,0.30,8.05,34.2,61533.0,...,5.7026,"POLYGON ((145.06733 -37.82204, 145.06682 -37.8...",2046.0,2016,207011155,2811.0,False,885,207011155,368
228,212041311,0.107748,0.086868,0.036706,0.036706,908,0.44,3.81,17.0,37323.0,...,61.8243,"POLYGON ((145.19335 -37.98662, 145.19353 -37.9...",1243.0,2016,212041311,1596.0,False,4998,212041311,3206
266,213031348,0.131000,0.115641,0.045230,0.045230,946,0.39,4.65,16.7,44970.0,...,4.9670,"POLYGON ((144.88323 -37.78789, 144.88333 -37.7...",1379.0,2016,213031348,2023.0,False,2635,213031348,1633
300,214021380,0.195167,0.139384,0.034515,0.034515,983,0.37,5.31,21.9,44686.0,...,21.0928,"POLYGON ((145.03077 -38.22462, 145.03110 -38.2...",1440.0,2016,214021380,1842.0,False,2117,214021380,1169

In [69]:
sub8_all_info.to_csv("../data/sa2_old_sub8_513.csv",index = False)