Read csv

In [1]:
import pandas as pd
data_all = pd.read_csv("../data/sa2_old_all_513.csv")

In [2]:
data_all

,sa2_maincode_2016,compound_score,pos_score,neu_score,neg_score,fid,percentile_ratos_p20_p50_ratio,percentile_ratos_p80_p20_ratio,income_share_top_5pc_pc,median_aud,...,AREASQKM16,geometry,rnt_mrtgge_pymnts_cnss_avrge_mnthly_hshld_rntl_pymnt,yr,sa2_maincode_2016,rent_mortgage_payments_census_average_monthly_household_payment,low_income_card_censored,health_care_card,sa2_main16,jobseeker_payment
0,206011105,0.135939,0.120654,0.046423,0.046423,680,0.38,4.89,18.7,51576.0,...,5.1425,POLYGON ((144.9497404700001 -37.76276897499997...,1824.0,2016,206011105,2240.0,False,3644,206011105,1964
1,206011106,0.145158,0.114565,0.040679,0.040679,681,0.38,4.66,17.9,54618.0,...,2.1680,POLYGON ((144.9733986020001 -37.76204042699993...,1840.0,2016,206011106,2218.0,False,1617,206011106,829
2,206011107,0.161915,0.149488,0.055161,0.055161,682,0.38,4.84,18.5,50643.0,...,3.1795,"POLYGON ((144.934072298 -37.75969414599996, 14...",1494.0,2016,206011107,2144.0,False,1819,206011107,1011
3,206011108,0.110326,0.112907,0.052949,0.052949,683,0.39,4.76,17.8,50613.0,...,6.9346,POLYGON ((144.9484712550001 -37.73950874099995...,1642.0,2016,206011108,2135.0,False,3224,206011108,1767
4,206011109,0.220207,0.162807,0.048373,0.048373,684,0.39,4.62,17.8,55080.0,...,2.9887,"POLYGON ((144.93264106 -37.74226400099997, 144...",1609.0,2016,206011109,2136.0,False,951,206011109,459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,214011376,0.110310,0.148097,0.078747,0.078747,979,0.44,3.92,17.5,52393.0,...,19.8152,POLYGON ((145.2015461950001 -38.08045397199993...,1753.0,2016,214011376,1963.0,False,1164,214011376,561
300,214021380,0.195167,0.139384,0.034515,0.034515,983,0.37,5.31,21.9,44686.0,...,21.0928,POLYGON ((145.0307728790001 -38.22462099499995...,1440.0,2016,214021380,1842.0,False,2117,214021380,1169
301,214021381,0.216418,0.189506,0.055296,0.055296,984,0.33,6.43,26.5,54529.0,...,23.2077,"POLYGON ((145.072006856 -38.18709737099994, 14...",1923.0,2016,214021381,2422.0,False,1041,214021381,474
302,214021382,0.132294,0.124204,0.066461,0.066461,985,0.36,5.63,22.7,49040.0,...,30.2094,"POLYGON ((145.025843664 -38.25242421899998, 14...",1791.0,2016,214021382,2094.0,False,1335,214021382,623
303,214021385,0.210186,0.173260,0.052122,0.052122,988,0.42,4.18,18.2,47929.0,...,117.3540,POLYGON ((145.0928499620001 -38.23092745899993...,1360.0,2016,214021385,1743.0,False,1631,214021385,858

In [3]:
data_all.columns

Index(['sa2_maincode_2016', 'compound_score', 'pos_score', 'neu_score',
       'neg_score', 'fid', ' percentile_ratos_p20_p50_ratio',
       ' percentile_ratos_p80_p20_ratio', ' income_share_top_5pc_pc',
       ' median_aud', ' highest_quartile_pc', ' median_age_of_earners_years',
       ' sa2_code', ' third_quartile_pc', ' sa2_name',
       ' percentile_ratos_p80_p50_ratio', ' earners_persons',
       ' gini_coefficient_coef', ' income_share_top_1pc_pc',
       ' lowest_quartile_pc', ' mean_aud', ' sum_aud', ' second_quartile_pc',
       ' percentile_ratos_p10_p50_ratio', ' income_share_top_10pc_pc',
       'SA2_MAIN16', 'SA2_5DIG16', 'SA2_NAME16', 'SA3_CODE16', 'SA3_NAME16',
       'SA4_CODE16', 'SA4_NAME16', 'GCC_CODE16', 'GCC_NAME16', 'STE_CODE16',
       'STE_NAME16', 'AREASQKM16', 'geometry',
       'rnt_mrtgge_pymnts_cnss_avrge_mnthly_hshld_rntl_pymnt', ' yr',
       ' sa2_maincode_2016',
       ' rent_mortgage_payments_census_average_monthly_household_payment',
       'low_income_card_censored', ' health_care_card', ' sa2_main16',
       ' jobseeker_payment'],
      dtype='object')

In [4]:
columns_clean  =['sa2_maincode_2016',' sa2_name' ,'compound_score', 'pos_score', 'neu_score',
       'neg_score', 'fid', 
       ' median_aud',  
        'geometry',
       ' rent_mortgage_payments_census_average_monthly_household_payment', ' health_care_card',
       ' jobseeker_payment']

In [5]:
data_clean = data_all[columns_clean]

In [6]:
data_clean

,sa2_maincode_2016,sa2_name,compound_score,pos_score,neu_score,neg_score,fid,median_aud,geometry,rent_mortgage_payments_census_average_monthly_household_payment,health_care_card,jobseeker_payment
0,206011105,Brunswick,0.135939,0.120654,0.046423,0.046423,680,51576.0,POLYGON ((144.9497404700001 -37.76276897499997...,2240.0,3644,1964
1,206011106,Brunswick East,0.145158,0.114565,0.040679,0.040679,681,54618.0,POLYGON ((144.9733986020001 -37.76204042699993...,2218.0,1617,829
2,206011107,Brunswick West,0.161915,0.149488,0.055161,0.055161,682,50643.0,"POLYGON ((144.934072298 -37.75969414599996, 14...",2144.0,1819,1011
3,206011108,Coburg,0.110326,0.112907,0.052949,0.052949,683,50613.0,POLYGON ((144.9484712550001 -37.73950874099995...,2135.0,3224,1767
4,206011109,Pascoe Vale South,0.220207,0.162807,0.048373,0.048373,684,55080.0,"POLYGON ((144.93264106 -37.74226400099997, 144...",2136.0,951,459
...,...,...,...,...,...,...,...,...,...,...,...,...
299,214011376,Skye - Sandhurst,0.110310,0.148097,0.078747,0.078747,979,52393.0,POLYGON ((145.2015461950001 -38.08045397199993...,1963.0,1164,561
300,214021380,Mornington,0.195167,0.139384,0.034515,0.034515,983,44686.0,POLYGON ((145.0307728790001 -38.22462099499995...,1842.0,2117,1169
301,214021381,Mount Eliza,0.216418,0.189506,0.055296,0.055296,984,54529.0,"POLYGON ((145.072006856 -38.18709737099994, 14...",2422.0,1041,474
302,214021382,Mount Martha,0.132294,0.124204,0.066461,0.066461,985,49040.0,"POLYGON ((145.025843664 -38.25242421899998, 14...",2094.0,1335,623
303,214021385,Somerville,0.210186,0.173260,0.052122,0.052122,988,47929.0,POLYGON ((145.0928499620001 -38.23092745899993...,1743.0,1631,858

In [7]:
data_clean.to_csv("../data/sa2_old_all_clean_513.csv",index = False)

In [8]:
name_list = ["Melbourne","Brunswick","Docklands","Footscray",'Surrey Hills (West) - Canterbury',"Camberwell","Dandenong","Mornington"]

In [9]:
sub8_clean_info = data_clean[data_clean[" sa2_name"].isin(name_list)]

In [10]:
sub8_clean_info

,sa2_maincode_2016,sa2_name,compound_score,pos_score,neu_score,neg_score,fid,median_aud,geometry,rent_mortgage_payments_census_average_monthly_household_payment,health_care_card,jobseeker_payment
0,206011105,Brunswick,0.135939,0.120654,0.046423,0.046423,680,51576.0,POLYGON ((144.9497404700001 -37.76276897499997...,2240.0,3644,1964
13,206041118,Docklands,0.143549,0.111991,0.037171,0.037171,693,51342.0,POLYGON ((144.9323839900001 -37.81927400699993...,2408.0,851,531
17,206041122,Melbourne,0.135247,0.096241,0.028379,0.028379,697,28068.0,"POLYGON ((144.964889649 -37.80687042299996, 14...",1841.0,2725,1672
44,207011149,Camberwell,0.123440,0.110495,0.050475,0.050475,724,57447.0,POLYGON ((145.0576189940001 -37.82653699599996...,2718.0,1389,555
50,207011155,Surrey Hills (West) - Canterbury,0.152065,0.139154,0.053066,0.053066,730,61533.0,POLYGON ((145.0673334690001 -37.82203638999994...,2811.0,885,368
228,212041311,Dandenong,0.107748,0.086868,0.036706,0.036706,908,37323.0,POLYGON ((145.1933482950001 -37.98661503499994...,1596.0,4998,3206
266,213031348,Footscray,0.131000,0.115641,0.045230,0.045230,946,44970.0,POLYGON ((144.8832274690001 -37.78789032899994...,2023.0,2635,1633
300,214021380,Mornington,0.195167,0.139384,0.034515,0.034515,983,44686.0,POLYGON ((145.0307728790001 -38.22462099499995...,1842.0,2117,1169

In [11]:
#extraction method
sub8_clean_info.loc[300]

sa2_maincode_2016                                                                                           214021380
 sa2_name                                                                                                  Mornington
compound_score                                                                                               0.195167
pos_score                                                                                                    0.139384
neu_score                                                                                                   0.0345151
neg_score                                                                                                   0.0345151
fid                                                                                                               983
 median_aud                                                                                                     44686
geometry                                                            POLYGON ((145.0307728790001 -38.22462099499995...
 rent_mortgage_payments_census_average_monthly_household_payment                                                 1842
 health_care_card                                                                                                2117
 jobseeker_payment                                                                                               1169
Name: 300, dtype: object

In [12]:
sub8_clean_info.loc[300]["compound_score"]

0.19516697819314666

In [13]:
list_compound = sub8_clean_info["compound_score"]

In [14]:
list_compound

0      0.135939
13     0.143549
17     0.135247
44     0.123440
50     0.152065
228    0.107748
266    0.131000
300    0.195167
Name: compound_score, dtype: float64

In [15]:
neu = 1 - sub8_clean_info["pos_score"] - sub8_clean_info["neg_score"]
sub8_clean_info["neu_score"] = neu

<ipython-input-15-c6da8d4f0b01>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub8_clean_info["neu_score"] = neu

In [16]:
sub8_clean_info.to_csv("../data/sa2_old_clean_sub8_513.csv",index = False)